refactor modules/packages structure
valentynmalyi/geometry pull request #16
Opened 2022-05-09 15:22 UTC by lightspeed69

2022-05-09 16:18 UTC, lightspeed69 commented
1. triangle exception
2. vector is child class for linesegment
3. add test for Point Triangle exceptions

2022-05-12 17:00 UTC, lightspeed69 commented
Point 1, 3 are done. Point 2 is cancelled

2022-05-12 17:54 UTC, valentynmalyi requested changes

2022-05-12 17:54 UTC, valentynmalyi commented on line/line_segment.py
> +        return f"A({self.a.x},{self.b.y}), B({self.b.x},{self.b.y})"
Here you can use f"{self.a}"

2022-05-12 17:54 UTC, valentynmalyi commented on test/test_triangle/test_triangle.py
> +                Triangle(a, b, c)
You don't call _validate_is_line method

2022-05-12 17:54 UTC, valentynmalyi commented on test/test_triangle/test_triangle.py
> +            RightTriangle(Point(0, 0), Point(0, 0), Point(0, 0))
_validate_is_point

2022-05-12 17:54 UTC, valentynmalyi commented on test/test_triangle/test_triangle.py
> +            RightTriangle(Point(3, 3), Point(1, 0), Point(0, 2))
_validate_is_right

2022-05-12 17:54 UTC, valentynmalyi commented on triangle/triangle.py
> +            self._validate_line_segment(a, b, c)
I think this isn't enough
(0,0) (0,1) (0,2) isn't a triangle

2022-05-12 17:54 UTC, valentynmalyi commented on triangle/triangle.py
> +        if not isclose(side[2] ** 2, side[1] ** 2 + side[0] ** 2):
Here you can use square_lenght

2022-05-12 17:54 UTC, valentynmalyi commented on triangle/triangle.py
> +        side = sorted([LineSegment(a, b).length, LineSegment(b, c).length, LineSegment(a, c).length])
x,y,z = [1,2,3]

2022-05-12 17:56 UTC, valentynmalyi commented on triangle/triangle.py
> +        side = sorted([LineSegment(a, b).length, LineSegment(b, c).length, LineSegment(a, c).length])
add TestPoint:test__eq__

2022-05-15 16:00 UTC, lightspeed69 commented on line/line_segment.py
> +        return f"A({self.a.x},{self.b.y}), B({self.b.x},{self.b.y})"
done

2022-05-15 16:49 UTC, lightspeed69 commented on triangle/triangle.py
> +        side = sorted([LineSegment(a, b).length, LineSegment(b, c).length, LineSegment(a, c).length])
done

2022-05-15 16:49 UTC, lightspeed69 commented on triangle/triangle.py
> +            self._validate_line_segment(a, b, c)
done

2022-05-15 18:41 UTC, valentynmalyi approved these changes

2022-05-15 18:41 UTC, merged